project_id = "cscakblvipadupebrpkh"

[functions.simulate-topup]
verify_jwt = false

[functions.purchase-data]
verify_jwt = false

[functions.activate-agent]
verify_jwt = false

[functions.request-withdrawal]
verify_jwt = true

[functions.guest-purchase]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = true

[functions.retry-order]
verify_jwt = false

[functions.activate-subagent]
verify_jwt = false

[functions.manage-subagent]
verify_jwt = false

[functions.webhook-orders]
verify_jwt = false
